import { puzzleFromBitmap } from "./generator";
import type { Puzzle, Difficulty } from "./types";

interface Entry {
  id: string;
  title: string;
  bitmap: string[];
  /** Force a curated tier (overrides the auto-grader). */
  difficulty?: Difficulty;
  /** Flavour note explaining the title. */
  note?: string;
}

/**
 * Curated pixel-art puzzles. Every entry is verified by `tests/puzzles.test.ts`
 * to have exactly one solution AND to be solvable by pure logic (no guessing).
 * The difficulty shown to the player is computed by the grader.
 */
const ENTRIES: Entry[] = [
  // ---------- 5×5 ----------
  { id: "plus", title: "Plus", bitmap: ["..#..", "..#..", "#####", "..#..", "..#.."] },
  { id: "smiley", title: "Smiley", bitmap: [".###.", "#.#.#", "#####", "#.#.#", ".###."] },
  { id: "house", title: "House", bitmap: ["..#..", ".###.", "#####", "#.#.#", "#.#.#"] },
  { id: "tee", title: "Letter T", bitmap: ["#####", "..#..", "..#..", "..#..", "..#.."] },
  { id: "frame", title: "Frame", bitmap: ["#####", "#...#", "#...#", "#...#", "#####"] },
  { id: "heart-s", title: "Little Heart", bitmap: [".#.#.", "#####", "#####", ".###.", "..#.."] },
  { id: "gem", title: "Gem", bitmap: ["..#..", ".###.", "#####", ".###.", "..#.."] },
  { id: "arrow", title: "Arrow", bitmap: ["..#..", ".###.", "#.#.#", "..#..", "..#.."] },

  // ---------- 10×10 ----------
  {
    id: "heart",
    title: "Heart",
    bitmap: [
      ".##....##.",
      "####..####",
      "##########",
      "##########",
      "##########",
      ".########.",
      "..######..",
      "...####...",
      "....##....",
      "..........",
    ],
  },
  {
    id: "mushroom",
    title: "Mushroom",
    note: "A woodland toadstool — domed cap, gills under the rim, and a ringed stem.",
    bitmap: [
      "...###....",
      "..#####...",
      ".#######..",
      "#########.",
      "..#.#.#...",
      "...###....",
      "..#####...",
      "...###....",
      "...###....",
      "..#####...",
    ],
  },
  {
    id: "note",
    title: "Music Note",
    note: "An eighth note — slanted head, tall stem, and the flag curling off the top.",
    bitmap: [
      "......##.....",
      "......####...",
      "......#.###..",
      "......#.####.",
      "......#..###.",
      "......#..##..",
      "......#..#...",
      "......#......",
      "......#......",
      "....###......",
      "..#####......",
      ".#####.......",
      ".###.........",
    ],
  },
  {
    id: "ghost",
    title: "Ghost",
    note: "A drifting wisp — hooded head, one eye, and a tail trailing off behind it.",
    bitmap: [
      "....##....",
      "...####...",
      "..######..",
      "..#.###...",
      "..######..",
      "...#####..",
      "....####..",
      "...###....",
      "..##......",
      ".#........",
    ],
  },
  {
    id: "cup",
    title: "Coffee Cup",
    bitmap: [
      "..........",
      ".#######..",
      ".#.....#.#",
      ".#.....###",
      ".#.....#.#",
      ".#.....#..",
      ".#######..",
      "..#####...",
      "..........",
      ".#######..",
    ],
  },
  {
    id: "balloon",
    title: "Balloon",
    bitmap: [
      "...####...",
      "..######..",
      ".########.",
      ".########.",
      ".########.",
      "..######..",
      "...####...",
      "....##....",
      "....##....",
      "....##....",
    ],
  },
  {
    id: "key",
    title: "Key",
    bitmap: [
      ".####.....",
      ".#..#.....",
      ".#..#.....",
      ".####.....",
      "..##......",
      "..##......",
      "..###.....",
      "..##......",
      "..###.....",
      "..##......",
    ],
  },
  {
    id: "bird",
    title: "Bird",
    bitmap: [
      "..........",
      ".##.......",
      ".####.....",
      "..######..",
      ".########.",
      "..######.#",
      "...####.##",
      "....##....",
      "....#.....",
      "..........",
    ],
  },
  {
    id: "umbrella",
    title: "Umbrella",
    bitmap: [
      "..........",
      "...####...",
      "..######..",
      ".########.",
      "##########",
      "....#.....",
      "....#.....",
      "....#.....",
      "...##.....",
      "..##......",
    ],
  },

  // ---------- 15×15 ----------
  {
    id: "tree",
    title: "Pine Tree",
    bitmap: [
      ".......#.......",
      "......###......",
      "......###......",
      ".....#####.....",
      ".....#####.....",
      "....#######....",
      "....#######....",
      "...#########...",
      "...#########...",
      "..###########..",
      "..###########..",
      ".#############.",
      ".......#.......",
      ".......#.......",
      ".....#####.....",
    ],
  },
  {
    id: "heart-l",
    title: "Big Heart",
    bitmap: [
      "...###...###...",
      "..#####.#####..",
      ".#############.",
      ".#############.",
      ".#############.",
      ".#############.",
      "..###########..",
      "...#########...",
      "....#######....",
      ".....#####.....",
      "......###......",
      ".......#.......",
      "...............",
      "...............",
      "...............",
    ],
  },
  {
    id: "snowman",
    title: "Snowman",
    bitmap: [
      "......###......",
      ".....#####.....",
      ".....#.#.#.....",
      ".....#####.....",
      "......#.#......",
      "......###......",
      ".....#####.....",
      "....#######....",
      "....#######....",
      "....#######....",
      "...#########...",
      "...#########...",
      "...#########...",
      "....#######....",
      ".....#####.....",
    ],
  },
  {
    id: "diamond",
    title: "Diamond",
    bitmap: [
      ".......#.......",
      "......###......",
      ".....#####.....",
      "....#######....",
      "...#########...",
      "..###########..",
      ".#############.",
      "###############",
      ".#############.",
      "..###########..",
      "...#########...",
      "....#######....",
      ".....#####.....",
      "......###......",
      ".......#.......",
    ],
  },
  {
    id: "anchor",
    title: "Anchor",
    bitmap: [
      ".......#.......",
      "......#.#......",
      ".......#.......",
      ".....#####.....",
      ".......#.......",
      ".......#.......",
      ".......#.......",
      ".......#.......",
      "#......#......#",
      "#......#......#",
      "##.....#.....##",
      ".##...###...##.",
      "..###########..",
      "....#######....",
      ".....#####.....",
    ],
  },

  // ---------- Extra Hard (need contradiction / hypothesis reasoning) ----------
  {
    id: "letter-a",
    title: "Letter A",
    bitmap: [".###.", "#...#", "#####", "#...#", "#...#"],
  },
  {
    id: "cat",
    title: "Cat",
    note: "A cat sitting upright — pointy ears, two eyes, and a tail curling to the right.",
    bitmap: [
      "#........#",
      "##......##",
      ".########.",
      ".#.####.#.",
      ".########.",
      ".########.",
      ".########.",
      ".#######..",
      ".#######.#",
      ".######.##",
    ],
  },
  {
    id: "static",
    title: "Static",
    note: "Named for TV static — there's no picture, just snow you must reason your way through.",
    bitmap: [
      "...#......",
      ".##...##.#",
      "...##.....",
      "####.....#",
      ".##.##.###",
      "##..##....",
      ".....##..#",
      "..#.##.##.",
      "###..#..#.",
      "#####..#.#",
    ],
  },
  {
    id: "cipher",
    title: "Cipher",
    note: "Named because the grid reads like rows of an encrypted message — only logic decodes it.",
    bitmap: [
      "..##..#.##",
      "#.......##",
      "##...##.#.",
      "###.....#.",
      "....#.#..#",
      ".##.##.#.#",
      ".##.###...",
      "#.#..###.#",
      "#........#",
      ".....#....",
    ],
  },
  {
    id: "labyrinth",
    title: "Labyrinth",
    note: "Named for its maze-like tangle of corridors and dead ends.",
    bitmap: [
      ".#....##.#..",
      ".....#.#.#..",
      "..##.####...",
      "..##..#..##.",
      "..#.###..###",
      "..#...##.###",
      "#.##......#.",
      ".###..##....",
      "#####..#..##",
      "#.#....#.#.#",
      ".#..##...##.",
      ".#......##.#",
    ],
  },
  {
    id: "riddle",
    title: "Riddle",
    note: "There's no obvious shape — the puzzle itself is the riddle.",
    bitmap: [
      "#..#.#..#.",
      ".##..##.##",
      "..#.#.###.",
      ".#.#....#.",
      ".###..#..#",
      "..#.##..#.",
      "...###.##.",
      "....##....",
      ".##.##....",
      "###.#.####",
    ],
  },
  {
    id: "enigma",
    title: "Enigma",
    note: "Named for the Enigma machine — an inscrutable cipher you crack one forced cell at a time.",
    bitmap: [
      "#.....##.#..#",
      "##.##.##....#",
      "..#.#.#..##.#",
      "##.#.#.#..#..",
      "#.#..#..##..#",
      "##..##...##.#",
      "#####...#...#",
      "##.##...#.#..",
      "..#.###.####.",
      ".###..#...#..",
      "#.#....##.###",
      "##.##.##...#.",
      "##.#..###.#..",
    ],
  },

  // ---------- MAX (large, brutal, contradiction-heavy — the top tier) ----------
  {
    id: "obsidian",
    title: "Obsidian",
    note: "A dense slab of black glass — 14×14 with no foothold but pure deduction.",
    bitmap: [
      "#.#....#..##..",
      "..##...##....#",
      ".......##..##.",
      "#..#.#.#...##.",
      "......#.####.#",
      "..###.#.##....",
      "#..####...##..",
      "##...#..#...##",
      "..##.##.#..#..",
      "##.#..##.#.##.",
      "#.#..#...###..",
      "###.#.#...##..",
      "###...#.#.###.",
      "#..#.#.####.##",
    ],
  },
  {
    id: "leviathan",
    title: "Leviathan",
    note: "A 15×15 sea-monster of a grid — vast, and it fights back.",
    bitmap: [
      ".....###.#.#..#",
      ".......####..#.",
      "##.###.....#.#.",
      "#...#...#.##..#",
      ".#.##..#...#...",
      "#..#.#..###...#",
      "#..#.#...#.####",
      "....#.#####..##",
      "#..#.##.#.#.##.",
      "..####..#..#.#.",
      "#.##.##.#.##.##",
      "..#.####.###..#",
      ".##..#.###..###",
      ".#.##..##....##",
      "#.#.######.#.#.",
    ],
  },
  {
    id: "nebula",
    title: "Nebula",
    note: "Scattered light across 15×15 — find the order hidden in the chaos.",
    bitmap: [
      "#.#.##.###.#..#",
      "###..#.#.#.....",
      "###..#.#.######",
      "..##..#.###...#",
      "##.##.#..#####.",
      "#.#.#.#.#...#..",
      ".#.#..#.#.#.##.",
      ".###.####.....#",
      "#.#....#.#.##.#",
      "..#..##..###..#",
      "###.##.#...####",
      ".#........##.#.",
      "...#.##.##.##..",
      ".#.#.#..#..#...",
      "..##.#..##...#.",
    ],
  },
];

// Titles that deliberately do NOT describe their picture (the abstract tiers
// keep their secrets); everything else earns the Name-hint badge.
const ABSTRACT_IDS = new Set([
  "static",
  "cipher",
  "labyrinth",
  "riddle",
  "enigma",
  "obsidian",
  "leviathan",
  "nebula",
]);

export const LIBRARY: Puzzle[] = ENTRIES.map((e) => {
  const { puzzle } = puzzleFromBitmap(e.bitmap, e.title, e.id, e.difficulty);
  return { ...puzzle, note: e.note, named: !ABSTRACT_IDS.has(e.id) };
});

export function getPuzzle(id: string): Puzzle | undefined {
  return LIBRARY.find((p) => p.id === id);
}

export function byDifficulty(d: Difficulty): Puzzle[] {
  return LIBRARY.filter((p) => p.difficulty === d);
}

export const DIFFICULTY_ORDER: Difficulty[] = ["easy", "medium", "hard", "expert", "max"];
